volumes:
  ny_taxi_postgres_data:
    driver: local
  kestra_postgres_data:
    driver: local
  kestra_data:
    driver: local
  kestra_tmp:
    driver: local

services:
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql
    depends_on:
      kestra:
        condition: service_started

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8085:80"
    depends_on:
      pgdatabase:
        condition: service_started

  kestra_postgres:
    image: postgres:18
    volumes:
      - kestra_postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:v1.1
    pull_policy: always
    # Note that this setup with a root user is intended for development purpose.
    # Our base image runs without root, but the Docker Compose implementation needs root to access the Docker socket
    # To run Kestra in a rootless mode in production, see: https://kestra.io/docs/installation/podman-compose
    user: "root"
    command: server standalone
    volumes:
      - kestra_data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - kestra_tmp:/tmp/kestra-wd
    environment:
      SECRET_GCP_CREDS: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAia2VzdHJhLXNhbmRib3gtNDkwNTE2IiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiZTQyZWFkYjdiMmMwZmQzYzEzYjU0OGNmODdjZDQ1MzFjOTkxYzBjYiIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFETmFhTDlvN1NGYUFONlxuTGRBS3JjUjljWWlyeG03Ymw1elRrcThiUm9Venlka1lBZzVCN0VkbEZPT3B1KzJTRVZhSWhGVUU3UU1JVmhtRVxuVmw5Tmtsdy9jSnNsSHVNakRrR2tHY1RFTTZlMDFraTg2R0p5UVZROUdaUlFUdlFkaUhTcFNVRVZsSW9IeEZjRlxua1J5ckhVYjBmcDRQQmRSZEZDS0Joajh0R3dhSk1mR1pKM3FjeXB6NWdiS3BUZTJ5b3B1WDNIZCtHcHNhL1VKTFxuRzNGL0RJQ01KblEyYWVpN2h5NFMvQXVSNjZROGFwaXZ5a2lEaW1iaDFaM1JkakxDYmVDMDNnbHdrRzMxMkNLMFxudzJlQ21EdkwrWjBGSGRab05mM3BULzZUTHM5V2pOdHZ0V3VNUnJlVDBBVEpTRXJzK0dYQmtLRkppdmRoK3BUaVxuNmRYSTFFZFpBZ01CQUFFQ2dnRUFHM2REaHZ5cnQ2Ylh5QzkyQU9lSlBXaS82SkFJNUszYUYyUW1xOVA3SFppZ1xud1pnTXhmM004aFFmK09NYStndjljUldZdEtib1grWDdWWG1qRnFFNlduVTVHWGFPMG5JbWpzV3ZUTGpIZE9PdVxuS0N3K2RaNk1uL3JhblA1aG44MU9KQkNhZGtNOVRacVFORHRhQlB0T01JVDVwM0tWR2JrR2dDRXVNMTdJdWZGSlxuVkpNOUtiRkNIdUI3SlZuZzF4dFpOcVdNK25pUlEza29KamJGaU9NdUpFRkE4SHZhK0lHbWZZWEo0SWpvZ3V6UlxuYzJQOEUzMWhOeEFZOFNZbjR3cUJid3RSYm11RTREUFN2aXpGTHdyL3BKb2lSQzhWbjV4TW9ycGo5UDdvNm5zRVxuYkY4NUdNQjdkcjB6dEpjZFpOU2RaUDZDbmZ1cENrOUdrOFQwOUFHNGpRS0JnUURsV3Y1UldpODNTaGp3Z0pEcFxudStDKzNnWS9BQlpINTZIQVR2Z3BadFpyNFQyWE83cHk5dGdGUkdVYUVJMVVWeGZld0tCWGF6SnFickoxcmRaVFxuSlBJQkYzMy9ZUFArSi8ySURUVXZLN3NqVnFHZGUrbVF2ZVh6bXUzSWwrdFQ2RWdud2t3d3BRZFhBbWx5bGo3dVxua3BkTEE5R0VIQm56MldOZUpwUE45djBQY3dLQmdRRGxScFpBd0FKaGorWXptZHB0bWVrV1AzZWpOWnY3TlNnTFxuVHRDa3J0RUFGcU5xblhob2R5bDZPSHMxTnAzaFBUQStQTGF1RUo0eUE4dHRnN3dmUkNNRlNNOENKdFpqWGdEWVxudEYyS0hUQytYL2MvQWhTVXNvWWpES2JtelEwbHJWQkY5K3Fhb3pFZFZ6ZDNMc2JQOUJLU1JCcHlqZ3NPb3JwTlxuaFdZTU8yWkRBd0tCZ0FTV2lHWGFOdjJWSnVDUXdkVmJJOGpOcWpSU2JSK3RHNGc4VEN5UDJSUTVZa0VIT2RpWVxuNVlOZGRlUktsbmtzY05iTTVhZzZCYjBwVDdxWTZxT3BKb290RFNFeHNFL1NQdmtjd29hYUNsbFBuMVlHSjRyMFxuc1lmby9uNjN3MFpmYkNvWGNleTdNR1ZtTC9QUjI1cHNKa2lpMytzVG9OVkc4UHp1S3FEQkl4alBBb0dCQU5rdlxuYVd1Q3QzNjFzbW9WQnUybHl6K3c5V0tjaU5xSSt4cmpHUSszTGZJNGY2cWg2b3FDdnI2eFBEMG5OSjFGdWlwcVxubHQ0Q2plaHc0Y1ltOFJCcEdnZUtkZFhpOWxrQWxpcXhpSjRwa3AvMEJpRWdsbUJaVUdscE5iMFNacTdYSTJCMFxuUFQ4bzhZQ0t1dGJpYjZCVDR6ZTgzWlRBYTBiODdTQThDblB4M0tnREFvR0FaUVNYSGhkQ2srNnErYkI5ODgya1xuMzFFQ3FGVTVXRUc5SnhRY3JVN0Fjd3FaYlJXWjNwcnk4YjdsZFljZ2pUK0J4R3c1a0pqV1hlSWFqVzdxNWJNWFxuSEx3cGkzbE1ndFJ4U0FDK2ZhS3IvK3lRbnJvYzZiM3dGdkpmVUovaERvRmlhMWVPY2hjVUlUMG5Zbi9wK0lmZ1xuSEpvbk5KTXo4TEFmWWN6MmduZGNVWXM9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAia2VzdHJhLW55QGtlc3RyYS1zYW5kYm94LTQ5MDUxNi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTQwMTk3MzAzOTE3NTkzMTE5OTkiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2tlc3RyYS1ueSU0MGtlc3RyYS1zYW5kYm94LTQ5MDUxNi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQo="
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra_postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basicAuth:
              username: "admin@kestra.io" # it must be a valid email address
              password: Admin1234!
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
          secretsManager:
            type: env-var
          ai:
            type: gemini
            gemini:
              model-name: gemini-2.5-flash
              api-key: "AIzaSyC60bm6wTfetP5AK92lVEgnjm8uBuBDgPA"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      kestra_postgres:
        condition: service_started
    